version: '3.8'

services:
  development:
    build:
      args:
        UID: ${UID}
        GID: ${GID}
        USER: ${USER}
        REPO: ${REPO}
        WS: ${WS}
      context: .
      dockerfile: Dockerfile
    command: bash -c "source /usr/share/colcon_argcomplete/hook/colcon-argcomplete.bash &&
                      colcon mixin add default https://raw.githubusercontent.com/colcon/colcon-mixin-repository/master/index.yaml &&
                      colcon mixin update &&
                      export PATH="/usr/lib/ccache:$PATH" &&
                      source /opt/ros/noetic/setup.bash &&
                      sudo chown -R ${GID}:${UID} src &&
                      bash"
    container_name: ${USER}-${REPO}-dev
    environment:
      - DISPLAY=${DISPLAY}
      - QT_X11_NO_MITSHM=1
      - ROS_DOMAIN_ID=0
      - TERM=xterm-256color
    extra_hosts:
      - ${REPO}-dev:127.0.0.1
    hostname: ${REPO}-dev
    image: ${REPO}-dev:latest
    network_mode: host
    privileged: true
    volumes:
      - ~/.ssh:${HOME}/.ssh:ro
      - ~/.gitconfig:${HOME}/.gitconfig:ro
      - ${PWD}:${HOME}/ws/src/${REPO}
      - ${WS}/src/remo_description:${HOME}/ws/src/remo_description
      - ${WS}/src/rplidar_ros:${HOME}/ws/src/rplidar_ros
      - ${WS}:${HOME}/ws
      - ~/:${HOME}/ws/src/${REPO}
      - ~/.${REPO}/ccache:${HOME}/.ccache
      - /tmp/.X11-unix:/tmp/.X11-unix:ro
      - /etc/group:/etc/group:ro
      - /etc/passwd:/etc/passwd:ro
      - /etc/shadow:/etc/shadow:ro
    working_dir: ${HOME}/ws
